name: Build Image and Deploy to GHCR

on:
  workflow_dispatch:

  release:
    types: [created]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@main

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.PAT}}

      - name: Get Version
        id: get_version
        run: |
          RAW_VERSION="${{ github.event.release.tag_name }}"
          VERSION="${RAW_VERSION#v}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "Version = ${VERSION}"
      
      - name: Build Image
        run: |
          docker build . --tag ghcr.io/mattblackonly/tubetube:latest
          docker push ghcr.io/mattblackonly/tubetube:latest

          docker tag ghcr.io/mattblackonly/tubetube:latest ghcr.io/mattblackonly/tubetube:${{ env.VERSION }}
          docker push ghcr.io/mattblackonly/tubetube:${{ env.VERSION }}
